import PolicyPage from "../components/PolicyPage";

const sections = [
  {
    heading: "Electronic Record and Acceptance",
    paragraphs: [
      "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
      "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.gojobin.com website.",
      `The domain name www.gojobin.com (hereinafter referred to as "Website") is owned and operated by Vidi Meth Digital Services (OPC) Private Limited a company incorporated under the Companies Act, 1956 with its registered office at 147 Aambagan Road, Sakchi, Jamshedpur - 831001, Jharkhand, India (hereinafter referred to as "GoJobin"). Corporate Identity Number of the company is U52100JH2017OPC009718.`,
      `Your use of the GoJobin and services and tools are governed by the following terms and conditions (hereinafter "Terms of Use") as applicable to the GoJobin including the applicable policies which are incorporated herein by way of reference.`,
      `For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to the User to surf the Website. The term "We", "Us", "Our" shall mean Vidi Meth Digital Services (OPC) Private Limited.`,
      "By mere accessing or using of the Website, users signify they have carefully read, understood, agree, without limitation or qualifications to be bound by these Terms of Use. When user transact or avail any of the services provided by Us through the Website or browse through the website, (e.g. Product Reviews, associates parties), in present or future, users accept and agree to be bound of these Terms of Use, rules, guidelines, policies, terms, and conditions of GoJobin's service.",
      "We reserve the right, to changed, edited, altered, amended, modified, add or remove portions of these Terms of Use, at any time without any prior written notice to you. You shall ensure to review these Terms of Use periodically for updates/changes. Your continued use of the Website following the modification will mean that You accept and agree to the revisions. As long as you comply with these Terms of Use (rules, guidelines, policies, terms, and conditions), we grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.",
      "ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. If you do not agree with these Terms of Use, Please do not use the website. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by GoJobin Policies, inter alia Privacy Policy (available at Privacy ) of the Company, which would be amended from time to time.",
    ],
  },
  {
    heading: "Eligibility",
    paragraphs: [
      "The user should have completed 18 years of age and be competent to enter into a contract under Indian contract law. The Services are not available to minors under the age of eighteen (18) or to any Users suspended or removed from the GoJobin system by GoJobin for any reason whatsoever.",
      "If you are a minor i.e. under 18 years of age who is intending to avail the services of the Website should do so through his or her legal guardian in accordance with applicable law.",
    ],
    items: [
      "GoJobin reserves the right to terminate your membership and / or refuse access to use the Services offered at the Website to new Users or to terminate access granted to existing Users at any time without according any reasons for doing so.",
      "You shall not have more than one active Account (defined hereunder) on the Website.",
      "You are prohibited from selling, trading, or otherwise transferring Your Account to another person.",
    ],
  },
  {
    heading: "User Account, Password and Security",
    paragraphs: [
      "You may access and use the Website, You shall be responsible for maintaining the confidentiality and security of the Account Information, and are fully responsible for all activities that occur under Your log-in ID (Display Name) and Password.",
      "You agree to:",
    ],
    items: [
      {
        label: "i.",
        text: "Immediately notify GoJobin of any unauthorized use of Your Account Information or any other breach of security, and",
      },
      {
        label: "ii.",
        text: "Ensure that You exit from Your Account at the end of each session.",
      },
      "GoJobin cannot and will not be liable for any loss or damage arising from Your failure to comply with this section. You may be held liable for losses incurred by GoJobin or any other user of or visitor to the Website due to authorized or unauthorized use of Your Account as a result of Your failure in keeping Your Account Information secure and confidential.",
      "You shall ensure that the Account Information provided by You in the Website's registration form is complete, accurate and up-to-date. Use of another user's Account Information for availing the Services is expressly prohibited.",
      "If You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.",
    ],
  },
  {
    heading: "User Jurisdiction",
    paragraphs: [
      "If Website is used from outside India, it is entirely at the user's risk. The Website makes no representation that its contents and other features are available or otherwise suitable for use outside India.",
      "If the Website is used and accessed from or in locations outside India, the user shall ensure that the usage of the Website is legal and valid under applicable law of the user's location.",
      "The user agrees to undertake all liabilities, responsibilities and consequences under applicable law in connection with the use of the Website from or in any location outside India.",
      "The user accessing the Website from any location outside India agrees and consents to enter into separate or additional terms as may be required by GoJobin at any time.",
    ],
  },
  {
    heading: "Communications",
    paragraphs: [
      "When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.",
    ],
  },
  {
    heading: "Platform for Transaction and Communication",
    paragraphs: [
      "Platform for Communication the Website is only a venue where Users may meet and interact with one another for their transactions. GoJobin is not and cannot be a party to or control in any manner any transaction between two Users of the Website.",
      "Consequently:",
    ],
    items: [
      {
        label: "i.",
        text: "All commercial/contractual terms are offered by and agreed to between users of the website alone.",
      },
      {
        label: "ii.",
        text: "GoJobin does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the services proposed to be sold or offered to be sold or purchased on the Website.",
      },
      {
        label: "iii.",
        text: "GoJobin does not implicitly or explicitly support or endorse the sale or purchase of any services on the Website. GoJobin accepts no liability for any errors or omissions, whether on behalf of itself or third parties.",
      },
      {
        label: "iv.",
        text: "GoJobin platform shall not be utilized to upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail by the user. GoJobin reserves the right to filter and monitor and block the emails sent by users using the servers maintained by GoJobin to relay emails. All attempts shall be made by GoJobin and the user to abide by International Best Practices in containing and eliminating Spam.",
      },
      {
        label: "v.",
        text: "Users shall not spam the database maintained by GoJobin or indiscriminately and repeatedly forward mail that may be considered spam etc. Any conduct of the user in violation of this clause shall entitle GoJobin to forthwith terminate all services to the user without notice and to forfeit any amounts paid by him.",
      },
      {
        label: "vi.",
        text: "The user shall not upload, post, transmit, publish, or distribute any material or information that is unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libellous, vulgar, obscene, or racially, ethnically, or otherwise objectionable.",
      },
      {
        label: "vii.",
        text: "The User is solely responsible for maintaining confidentiality of the User password and user identification and all activities and transmission performed by the User through his user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and GoJobin assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line.",
      },
      {
        label: "viii.",
        text: "The User/Subscriber/Visitor to GoJobin and/or its affiliated websites does hereby specifically agree that he/she shall, at all times, comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, bye laws and notifications made there under, while assessing or feeding any resume/ insertion or information/data into the computers, computer systems or computer network of GoJobin. The said User/ subscriber/ visitor to GoJobin and/or its affiliated websites does further unequivocally declare that in case he violates any provisions of the Information Technology Act, 2000 and/or rules, regulations, guidelines, byelaws and notifications made there under, he shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.",
      },
      {
        label: "ix.",
        text: "The user shall not infringe on any intellectual property rights of any person / entity or retain information / download any information from any computer system or otherwise with an intention to do so.",
      },
      {
        label: "x.",
        text: "GoJobin will make best efforts to do so but does not warrant that any of the websites or any affiliate site(s) or network system linked to it is free of any operational errors nor does it warrant that it will be free of any virus, computer contaminant, worm, or other harmful components. The subscription of a user shall be subject to Quotas as applicable and as advised. e-mails provided as part of contact details are expected to be genuine and access to such email accounts is available to authorized personnel only.",
      },
      {
        label: "xi.",
        text: "GoJobin shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user's account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.",
      },
      {
        label: "xii.",
        text: "Payments for the services offered by GoJobin shall be on a 100% advance basis. Refund if any will be at the sole discretion of GoJobin offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customers card/bank accounts. Gojobin.com gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only. GoJobin undertakes no liability for free services.",
      },
      {
        label: "xiii.",
        text: "In case a person using the world wide web/internet receives a spam or virus which includes a link to GoJobin or to any other site maintained, operated or owned by Vidi Meth Digital Services (OPC) Private Limited, it should not be held responsible for the same. GoJobin assumes no responsibility for such mails.",
      },
      {
        label: "xiv.",
        text: "GoJobin neither guarantees nor offers any warranty about the credentials bonafides, status or otherwise of the prospective employer/organization which downloads the resume/ insertion or information/data and uses it to contact the user. GoJobin would not be held liable for loss of any data technical or otherwise, or of the resume/ insertion or information/data or particulars supplied by user due to acts of god as well as reasons beyond its control like corruption of data or delay or failure to perform as a result of any cause(s) or conditions that are beyond GoJobin's reasonable control including but not limited to strikes, riots, civil unrest, govt. policies, tampering of data by unauthorized persons like hackers, distributed denial of service attacks, virus attacks, war and natural calamities.",
      },
      {
        label: "xvi.",
        text: "GoJobin undertakes to take all reasonable precautions at its end to ensure that there is no leakage/misuse of the password granted to the subscriber. It shall be the sole responsibility of the user to ensure that it uses the privacy setting options as it deems fit to debar / refuse access of the data fed by it, to such corporate entities individuals or consultants.",
      },
      {
        label: "xvii.",
        text: "User further represent that the products/services purchased are not for resale to others.",
      },
      {
        label: "xviii.",
        text: "GoJobin shall not and is not required to mediate or resolve any dispute or disagreement between employee and employers.",
      },
      {
        label: "xix.",
        text: "You release and indemnify GoJobin and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the website and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, GoJobin cannot take responsibility or control the information provided by other Users which is made available on the website. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website.",
      },
      "Please note that there could be risks in dealing with underage persons or people acting under false pretence.",
    ],
  },
  {
    heading: "User Conduct and Rules on the Website",
    paragraphs: [
      "The user agrees and undertakes that the reviews, comments and other information provided or posted or uploaded on the website are not false, incomplete, distorted, manipulated, fraudulent or misleading.",
      "The user agrees, undertakes and confirms that when using or accessing the website shall be strictly governed by the following binding principle:",
    ],
    items: [
      {
        label: "1.",
        text: "User will not to host, display, upload, modify, publish, transmit, update or share any information (objectionable contents) that:",
        children: [
          {
            label: "i.",
            text: "Belongs to another person and to which You does not have any right to;",
          },
          {
            label: "ii.",
            text: "Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;",
          },
          {
            label: "iii.",
            text: "Harms minors in any way;",
          },
          {
            label: "iv.",
            text: "Is misleading in any way;",
          },
          {
            label: "v.",
            text: "Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity;",
          },
          {
            label: "vi.",
            text: "Is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;",
          },
          {
            label: "vii.",
            text: "Harasses or advocates harassment of another person;",
          },
          {
            label: "viii.",
            text: `Involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";`,
          },
          {
            label: "ix.",
            text: "Promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;",
          },
          {
            label: "x.",
            text: "Infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen items;",
          },
          {
            label: "xi.",
            text: "Contain software viruses or any other computer code, files, programs, Trojan horses, worms, time bombs, cancel bots, easter eggs or other programming routines that may damage, interfere with, intercept or expropriate any system, data or personal information;",
          },
          {
            label: "xii.",
            text: "Disrupt or interfere with the security of, or otherwise cause harm to, the website, systems resources, accounts, passwords, servers or networks connected to or accessible through the websites or any affiliated or linked sites;",
          },
          {
            label: "xiii.",
            text: "Use the Website or Content for any purpose that is unlawful or prohibited by the Agreement, or to solicit any illegal activity or other activity which infringes the rights of GoJobin or other third parties;",
          },
          {
            label: "xiv.",
            text: "Tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;",
          },
          {
            label: "xv.",
            text: "Solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;",
          },
          {
            label: "xvi.",
            text: "Violates any law for the time being in force;",
          },
          {
            label: "xvii.",
            text: "Deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;",
          },
          {
            label: "xviii.",
            text: "Impersonate another person;",
          },
          {
            label: "xix.",
            text: "Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.",
          },
          {
            label: "xx.",
            text: "Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded;",
          },
          {
            label: "xxi.",
            text: "Violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;",
          },
        ],
      },
      {
        label: "2.",
        text: "The user shall not use any deep-link, page-scrape, robot, spider or other automatic device, program, algorithm, methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the website or any Content, or to reproduce or circumvent the navigational structure or presentation of the website or any Content, to obtain materials, documents or information through any means not purposely made available through the website.",
      },
      {
        label: "3.",
        text: "You shall not attempt to gain unauthorized access to any portion or feature of the website, or any other systems or networks connected to the website or to any server, computer, network, or to any services offered on or through the website, by hacking, password mining or any other illegitimate means.",
      },
      {
        label: "4.",
        text: "The user undertakes not to attempt to circumvent or modify any security technology or software that is part of the website. The user also agrees not to use any device, software or routine to interfere, engage or assist any other person, to circumvent or modify any security technology or software that is part of the website. The user should also not obscure or obstruct any features of the website. The user undertakes not to copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of the website or any part thereof without specific written permission from GoJobin.",
      },
      {
        label: "5.",
        text: "You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there under as applicable and amended from time to time, all applicable domestic laws, rules and regulations, and international laws, foreign exchange laws, statutes, ordinances and regulations regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service prohibited by applicable law including exchange control laws or regulations for the time being in force.",
      },
      {
        label: "6.",
        text: "You may need to install updates that we or any third party introduce from time to time to use the services, Products, Website including downloads and required functionality, such as bug fixes, patches, enhanced functions, missing plug-ins and new versions (collectively, Updates). Your use of the Products or Website you have installed requires that you have agreed to receive such automatically requested Updates.",
      },
      {
        label: "7.",
        text: "You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of GoJobin and / or others.",
      },
      {
        label: "8.",
        text: "You shall not engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products or services, including products or services related to that being displayed on the Website or related to us.",
      },
      {
        label: "9.",
        text: "It is possible that other users, including unauthorized users or hackers, may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such materials. It is also possible for others to obtain personal information about You due to your use of the Website, and the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website.",
      },
      "BY ACCEPTING THESE TERMS OF USE, YOU AGREE TO INDEMNIFY AND OTHERWISE HOLD HARMLESS GOJOBIN, ITS DIRECTORS, OFFICERS, EMPLOYERS, AGENTS, SUBSIDIARIES, AFFILIATES AND OTHER PARTNERS FROM ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF, RELATING TO, OR RESULTING FROM YOUR USE OF THE SERVICES OBTAINED THROUGH GOJOBIN.COM INCLUDING BUT NOT LIMITED TO INFORMATION PROVIDED BY YOU OR ANY OTHER MATTER RELATING TO GOJOBIN.COM. ANY REFERENCE TO DUTIES AND TAXES ETC IN THESE TERMS OF USE SHALL INCLUDE GOODS AND SERVICES TAX (HEREIN REFERRED AS GST) FROM THE DATE GST LAW IS IMPLEMENTED IN INDIA. ANY ADDITIONAL TAX LIABILITY ARISING ON ACCOUNT OF INTRODUCTION OF GST (WHETHER ON ACCOUNT OF INCREASE IN RATE OR ANY CHANGE BROUGHT IN BY THE NEW TAX REGIME) WOULD BE RECOVERED OVER AND ABOVE THE AGREED CONTRACT PRICE / SERVICE FEE.",
    ],
  },
  {
    heading: "Privacy",
    paragraphs: [
      "We view protection of your privacy policy as a very important principle. We understand clearly that You and Your Personal Information is one of our most important assets. We request to you please read this Privacy Policy carefully, by accessing or using our website.",
      "GoJobin respects your privacy and is committed to protecting it. For more details, please see our Privacy Policy at https://gojobin.com/privacy-policy/.",
      "If You object to Your Information being transferred or used in this way please do not use Website.",
    ],
  },
  {
    heading: "Fee",
    paragraphs: [
      "User can use and access the Website is free of charge. GoJobin reserves the right to change its Fee Policy from time to time, changes to the Fee Policy shall be posted on the Website notifying the users in advance.",
      "GoJobin reserves its right to charge the users for the use of the Website and provision of the services through the Website and all taxes as per applicable Indian law. All fees shall be quoted in Indian Rupees.",
    ],
  },
  {
    heading: "Payments Related Information",
    paragraphs: [
      "YOU ARE REQUESTED TO HONOUR YOUR PAYMENT OBLIGATIONS TO THE COMPANY.",
    ],
    items: [
      {
        label: "i.",
        text: "Payments for the services offered by the Platform shall be on a 100% advance basis. The payment for service once subscribed to by you is not refundable and any amount paid shall stand appropriated. Refund, if any, will be at the sole discretion of the Company.",
      },
      {
        label: "ii.",
        text: "User hereby irrevocably accepts to receive the tax invoice as soft copy through emails.",
      },
      {
        label: "iii.",
        text: "Notwithstanding anything contained in any other agreement or arrangement, by whatever name called, the performance obligation of the Company is to provide access of its on-line portal to the customer for the duration of the subscription period. Reference to any usage or any other performance obligation is to provide the upper limit for consumption, which by itself does not create any additional performance obligation upon the Company.",
      },
      {
        label: "iv.",
        text: "In the event of any suspension or termination of services on account of non-compliance of these Terms of Use, any payment made to the Company by you shall stand forfeited with immediate effect.",
      },
      {
        label: "v.",
        text: "While availing any payment method available on the Website, we will not be responsible or assume any liability for any loss or damage arising directly or indirectly to You due to:",
        children: [
          {
            label: "a.",
            text: "Lack of authorization for any transaction/s, or",
          },
          {
            label: "b.",
            text: "Any payment issues arising out of the transaction, or",
          },
          {
            label: "c.",
            text: "Exceeding the preset limit mutually agreed by You and between Bank/s, or",
          },
          {
            label: "d.",
            text: "Decline of transaction for any other reason/s",
          },
        ],
      },
      {
        label: "vi.",
        text: "All payments made against the purchases/services on Website by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Website will not facilitate transaction with respect to any other form of currency.",
      },
      {
        label: "vii.",
        text: "The User acknowledges and agrees that Company/Platform, at its sole discretion and without prejudice to other rights and remedies under applicable laws, shall be entitled to set off the amount excess paid by a subscriber/user against any amount(s) payable by User to Company under any other agreement or commercial relationship towards other products/services. The Company gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only.",
      },
      {
        label: "viii.",
        text: "You understand, accept and agree that the payment facility provided by Gojobin is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online payment, receiving payment through collection and remittance facility for transactions on the Gojobin Website using existing authorized banking infrastructure and Credit Card payment gateway networks.",
      },
      {
        label: "ix.",
        text: "Gojobin reserves the right to refuse to process Transactions by users with a prior history of questionable charges including breach of any agreements by user with Gojobin website, breach or violation of any law, or any charges imposed by Issuing Bank or breach of any policy.",
      },
      {
        label: "x.",
        text: "Users buying products online are redirected to third party gateways for completing payment transactions. These transactions happen on third party network and hence are not controlled by Company.",
      },
      {
        label: "xi.",
        text: "A User through his user identification shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and Company assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line.",
      },
      {
        label: "xii.",
        text: "The Company shall not be liable for any loss or damage sustained by reason of any disclosure, inadvertent or otherwise, of any information concerning the user's account and / or information relating to online transactions using credit cards / debit cards and / or their verification process and particulars, nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.",
      },
      {
        label: "xiii.",
        text: "The User or customer shall be required to promptly provide copy of TDS certificate to the Company as mandated under law for tax deducted at source from payments made to the Company. Any loss on account of non availment or disallowance of such TDS credit due to any lapse by User or customer shall entitle the company to seek reimbursement or indemnification.",
      },
      {
        label: "xiv.",
        text: "User shall comply with all applicable laws including, without limitation, Foreign Exchange Management Act, 1999, Exchange Control Manual as issued by Reserve Bank of India, Customs Act, Information Technology Act, 2000 as amended, Prevention of Money Laundering Act, 2002, Foreign Contribution Regulation Act, 1976, Income Tax Act, 1961, Export Import Policy of government of India, and the rules, notifications and policies made thereunder as applicable for using Payment Facility and Gojobin Website.",
      },
      {
        label: "xv.",
        text: "All valid credit, debit, cash card and other payment instruments are processed using a credit card payment gateway or appropriate payment system infrastructure and will also be governed by the terms and conditions agreed to between the Buyer and the respective Issuing Bank and payment instrument issuing company.",
      },
      {
        label: "xvi.",
        text: "All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which supports Payment Facility to provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer and the respective Issuing Bank.",
      },
    ],
  },
  {
    heading: "Intellectual Property Rights",
    paragraphs: [
      "All content included on the Website, such as text, graphics, logos, photographs, trademark, button icons, images, sound, music, artwork, audio clips, digital downloads, data compilations, and software, is the property of GoJobin, its affiliates, associates parties or service provider and is protected by India and international copyright, authors' rights and database right laws.",
      "The compilation of all content on the Website is the exclusive property of GoJobin, its affiliates, associates parties or service provider and is protected by laws of India and international copyright and database right laws.",
      "GoJobin grants the user a limited license to access and make personal use of this Website, but not to download, other than page caching, or modify it or any portion of it, except with express written consent of GoJobin. This license does not include resale or commercial use of the contents of the Website, collection and use of product listings, descriptions or prices, derivative use of this Website or its contents, or downloading or copying account information for the benefit of another party.",
      "The trademarks, logos and service marks displayed on the Website (Marks) are the property of GoJobin or its parent company and other associated parties and service provider. Users are not permitted to use the Marks without prior consent of GoJobin, associates, affiliates, content suppliers, users or any third party that may own the Marks.",
      "GoJobin owns all intellectual property rights to and into the trademark GoJobin and the Website, including rights, title and interest in copyright, related rights, patents, utility models, designs, know-how, trade secrets and inventions, goodwill, source code, meta tags, databases, text, content, graphics, icons, and hyperlinks.",
      "The users agree that they shall not use or apply for registration of any marks or domain names which are similar to the marks or domain names used in connection with the Website or owned by GoJobin.",
      "You shall not copy, reproduce, modify, alter, change, amend, transmit, broadcast, edit, revise, review, adapt, translate, distribute, perform, display, sell or otherwise deal with content or the intellectual property rights of the Website or content suppliers or third parties in any mode, medium or manner now known or developed in future without authorization from GoJobin.",
      "Users are strictly prohibited from framing or using framing techniques to enclose any content or intellectual property on the Website to illegally and unlawfully exploit the content or intellectual property rights owned by GoJobin or other associated parties, service provider or third party as the case is.",
    ],
  },
  {
    heading: "Disclaimer of Warranties and Liability",
    paragraphs: [
      "The User expressly agree that the use of the website is at the user's sole risk. The Website, service, content, user account and any third party content are provided by GoJobin on an as is and as available basis without any representation or warranty of any kind, express, implied, statutory or otherwise including implied warranties of title, non-infringement, accuracy, suitability, reliability, timelines, completeness, safety, performance, merchantability or fitness for a particular purpose permitted by applicable Indian law.",
      "Without prejudice to the foregoing paragraph, GoJobin does not warrant that:",
    ],
    items: [
      {
        label: "i.",
        text: "The website or the services will be uninterrupted, timely, secure or error-free,",
      },
      {
        label: "ii.",
        text: "This Website will be constantly available or available at all;",
      },
      {
        label: "iii.",
        text: "The information on this Website is complete, true, accurate or non-misleading,",
      },
      {
        label: "iv.",
        text: "Any errors or defects in the website or services will be corrected.",
      },
      "No advice or information, whether oral or written, obtained by you from GoJobin or through the website / content or from use of the services shall create any warranty not expressly stated in these Terms of Use.",
      "You expressly understand and agree that, to the maximum extent permitted by applicable law, GoJobin will not be liable to You in any way in relation to the Contents of, or unauthorised use of your account or account information in connection with the Website or any services, either with or without your knowledge.",
      "GoJobin does not warrant this site, nor makes any representations regarding the quality, accuracy or completeness of any data, information, Contents, materials or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.",
      "GoJobin shall not be responsible for delay, inability to use the website or related functionalities, provision of or failure to provide functionalities, or for any information, software, products, functionalities and related graphics obtained through the website or otherwise arising out of use of website, whether based on contract, tort, negligence, or strict liability.",
    ],
  },
  {
    heading: "Disclaimer of Online Availability, Impressions, and Click-through",
    paragraphs: [
      "In addition to the other disclaimers and limitations discussed in this notice, there are no guarantees and no warranties regarding online availability, impressions, and click-through of the Website, its web pages, the Application and any material, information, links, or content presented on the web pages that may be accessible through the Platform.",
      "Platform reserves the right, although it is under no obligation, to ensure that advertising sponsors and advertising must be approved by Company before posting any advertising material, information, links, content, banners, and graphics on the Platform. The same may be reported by contacting us.",
      "Any advertising should be related to interactive digital television and related subject areas. Company reserves the right to accept or reject any advertising sponsor or any advertising for any reason.",
    ],
  },
  {
    heading: "Purchasing and Ordering Disclaimer",
    items: [
      {
        label: "1.",
        text: "Make Your own decisions: If You are making or planning to make any decision, whether personal or business, based on content on the site, You should conduct independent verification before making Your important decision. In the case of listings or banners displaying content related to products, all decisions made would be entirely Your prerogative and Company does not claim to offer any advice, either legal or financial.",
      },
      {
        label: "2.",
        text: "Company does not take any ownership, directly or indirectly, towards any person whatsoever with respect to banners hosted on its Platform by its customers, which are strictly in the nature of sale of space by Platform. It has not carried out independent verification on authenticity or compliance requirements as may be required under any law for the time being in force for such images, banners or listings.",
      },
      {
        label: "3.",
        text: "Read These Terms: In purchasing/subscribing to a product/service offered on this platform you are advised to read these terms carefully before proceeding further. You understand and agree to the terms. If you do not understand and agree with these terms then do not place an order for a product/service.",
      },
      {
        label: "4.",
        text: "Pricing: All prices are subject to change without notice. Every effort has been made to ensure accurate pricing of products/services featured on our platform. In the event a part or accessory is ordered and the listed price has changed, you will be notified prior to processing your order.",
      },
      {
        label: "5.",
        text: "Purchase AS IS: All products/services are provided by the company on an as is basis with no representations or warranties of any kind from the company, including no warranties as to the nature and quantum of responses to any banner or listing displayed on the platform.",
      },
      {
        label: "6.",
        text: "Your responsibility; damage limits: YOU HAVE SOLE RESPONSIBILITY FOR USE OF THE PRODUCTS/SERVICES YOU PURCHASE THROUGH THIS PLATFORM. IN NO EVENT SHALL GOJOBIN.COM BE LIABLE TO YOU IN RELATION TO THE PRODUCTS/SERVICES, OR YOUR USE, MISUSE OR INABILITY TO USE THE PRODUCTS, FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, OR CONSEQUENTIAL DAMAGE INCLUDING LOSS OF BUSINESS, REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE; OR DIRECT DAMAGES IN EXCESS OF THE AMOUNT YOU PAID THE COMPANY FOR THE APPLICABLE PRODUCT/SERVICE.",
      },
    ],
  },
  {
    heading: "Indemnity",
    paragraphs: [
      "Users agree to indemnify and hold harmless GoJobin including affiliates, associates and their respective owners, licensee, directors, officers, agents, employees and partners from and against all actions, proceedings, claims, losses, damages and costs (including attorney fees) and other expenses suffered or incurred due to or attributable to or arising out of:",
    ],
    items: [
      {
        label: "i.",
        text: "Violation of any applicable law, rules or regulations;",
      },
      {
        label: "ii.",
        text: "Breach of any representations, warranties or covenants of the user;",
      },
      {
        label: "iii.",
        text: "Breach of this Terms of Use, Privacy Policy and other Policies;",
      },
      {
        label: "iv.",
        text: "The rights, including infringement of intellectual property rights, of a third party.",
      },
    ],
  },
  {
    heading: "Dispute Settlement",
    paragraphs: [
      "If any dispute arises between a user/users and Company arising out of use of the Platform or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these Terms, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by the Company.",
      "Decision of the arbitrator shall be final and binding on both the parties to the dispute. The place of arbitration shall be Jamshedpur, Jharkhand, India. The Arbitration & Conciliation Act, 1996 as amended, shall govern the arbitration proceedings.",
      "The Company will not be party to any legal proceedings between a User and a party contacted through the site. In case Company is made a party in any legal proceedings, costs will be recovered from the party on whose behest the Company is involved in the matter, to which it otherwise has no control. Company however will abide with any court order served on it through due process.",
    ],
  },
  {
    heading: "Local Laws",
    paragraphs: [
      "Gojobin controls and operates this website from its headquarters in Jamshedpur, India and makes no representation that the materials on the website are appropriate or available for use in other locations.",
      "If you use this website from other locations, you are responsible for compliance with applicable local laws including but not limited to export and import regulations of other countries.",
      "Unless otherwise explicitly stated, all marketing or promotional materials found on this website are solely directed to individuals, companies or other entities located in India and comply with the laws prevailing for the time being in force in India.",
      "Disputes if any shall be subject to the exclusive jurisdiction of Courts at Jamshedpur, Jharkhand.",
    ],
  },
  {
    heading: "Governing Law and Jurisdiction",
    paragraphs: [
      "The Terms of Use of this agreement shall be governed by Indian law and the courts at Jamshedpur, Jharkhand shall only have exclusive jurisdiction to resolve any disputes.",
    ],
  },
  {
    heading: "Links",
    paragraphs: [
      "The Site or third parties may provide links to other World Wide Web sites or resources. GoJobin has no control over such sites and resources and is not responsible for their availability, content, advertising, products or other materials.",
      "You acknowledge that GoJobin shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by use of or reliance on any content, goods or services available on or through any such site or resource.",
    ],
  },
  {
    heading: "Trademark, Copyright and Restriction",
    paragraphs: [
      "This site is controlled and operated by GoJobin and products are sold by You or associates parties. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights.",
      "Material on website is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means, whether directly or indirectly, and You must not assist any other person to do so.",
      "Without prior written consent of the owner, modification of materials, use of materials on any other website or networked computer environment, or use of materials for any purpose other than personal, non-commercial use is a violation of copyrights, trademarks and other proprietary rights and is prohibited.",
      "Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.",
    ],
  },
  {
    heading: "Miscellaneous",
    paragraphs: [
      "Amendment to these Terms: COMPANY RESERVES ITS RIGHT TO AMEND / ALTER OR CHANGE ALL OR ANY DISCLAIMERS OR TERM(S) OR CONDITION(S) OF AGREEMENTS AT ANY TIME WITHOUT ANY PRIOR NOTICE.",
      "Businesses, environment and technology evolve and in order to accommodate the changing nature of the environment in which we operate as well to provide for any additional features that may be introduced in future, these Terms may need modifications or additions.",
      "Such modifications or additions shall be effective immediately upon posting of the modified Terms of Use on the Site.",
      "You are advised to review the modified Terms of Use periodically to be aware of such modifications or additions and your continued access or use of the Site shall be deemed conclusive proof of your acceptance of these Terms of Use, as amended or modified from time to time.",
    ],
  },
  {
    heading: "Notice",
    paragraphs: [
      "All notices with respect to these Terms of Use from GoJobin will be served to You by email or by general notification on the website.",
      "Any notice provided to GoJobin pursuant to these Terms of Use should be sent to Grievance Officer at support@gojobin.com.",
    ],
  },
  {
    heading: "Grievance Officer",
    paragraphs: [
      "In case of any complaints or grievances, the user may contact the Grievance Officer at support@gojobin.com.",
    ],
  },
  {
    heading: "Contact Us",
    paragraphs: [
      "Please Contact Us at https://gojobin.com/contact-us/ for any questions, concerns or suggestions regarding our Privacy Policy at https://gojobin.com/privacy-policy/.",
    ],
  },
];

export const metadata = {
  title: "Terms and Condition | GoJobin",
  description: "GoJobin terms and condition for website access and services.",
};

export default function Terms() {
  return (
    <PolicyPage
      eyebrow="Legal"
      title="Terms and Condition"
      intro="Please read these terms and conditions carefully before accessing, browsing, or otherwise using GoJobin."
      sections={sections}
    />
  );
}
