import PolicyPage from "../components/PolicyPage";

const sections = [
  {
    heading: "Electronic record and acceptance",
    items: [
      "These Terms are an electronic record under the Information Technology Act, 2000 and applicable rules. This electronic record is generated by a computer system and does not require physical or digital signatures.",
      "By accessing, browsing, registering on, or using GoJobin, you confirm that you have read, understood, and agreed to be bound by these Terms and applicable policies.",
      "If you do not agree with these Terms, you should not use or access the website or services.",
      "GoJobin may change, modify, add, or remove portions of these Terms at any time. Continued use of the website after changes means that you accept the revised Terms.",
    ],
  },
  {
    heading: "Platform services",
    items: [
      "GoJobin provides an online platform for job seekers, employers, recruiters, and users to discover, list, post, enquire, and communicate about employment-related opportunities and services.",
      "GoJobin acts as an online intermediary and communication platform. Commercial or employment terms are offered and agreed between the relevant users, employers, candidates, recruiters, or third parties.",
      "GoJobin does not guarantee the truth, accuracy, availability, quality, legality, or completeness of any listing, job post, resume, employer information, candidate information, advertisement, or user-generated content.",
      "Users are advised to independently verify information and use their best judgment before acting on any listing, enquiry, communication, job post, or service.",
    ],
  },
  {
    heading: "Eligibility and user account",
    items: [
      "Users should be at least 18 years old and competent to enter into a contract under Indian law. Minors may use services only through a legal guardian and in accordance with applicable law.",
      "Users are responsible for maintaining the confidentiality of account information, login credentials, and password details.",
      "Users must immediately notify GoJobin of unauthorized account access or any breach of security and must ensure they exit from their account at the end of each session.",
      "Information provided during registration or use of the website must be complete, accurate, current, and lawful. GoJobin may suspend, terminate, or block access if information is false, inaccurate, incomplete, or violates these Terms.",
    ],
  },
  {
    heading: "User conduct and submissions",
    items: [
      "Users must post in the appropriate category or area and must comply with the Listing Policy, Privacy Policy, and all applicable laws.",
      "Users must not upload, post, transmit, or share illegal, defamatory, abusive, misleading, fraudulent, infringing, obscene, threatening, harmful, or unauthorized content.",
      "Users understand that they may be exposed to content from other users and agree that GoJobin is not responsible for the accuracy, usefulness, safety, or intellectual property rights relating to such content.",
      "Users agree to waive claims against GoJobin for user-generated content that may be inaccurate, offensive, indecent, objectionable, defamatory, or otherwise harmful.",
    ],
  },
  {
    heading: "Communications",
    items: [
      "When you use GoJobin or send emails, messages, data, or other communications, you consent to receive communications from GoJobin through electronic records, email, phone, SMS, or other permitted modes.",
      "By submitting your phone number or enquiry details, you consent to be contacted for service-related communication, job-related assistance, hiring-related assistance, account updates, or enquiry follow-up.",
    ],
  },
  {
    heading: "Fees and payments",
    items: [
      "Access to the website may be free for browsing, but GoJobin reserves the right to introduce, modify, or change fees for certain services from time to time.",
      "Any fees or payments, where applicable, shall be quoted in Indian Rupees and may be subject to applicable taxes under Indian law.",
      "If payment services are provided through third-party payment gateways or banking infrastructure, GoJobin will not be responsible for loss or damage arising from lack of authorization, payment decline, transaction limits, third-party gateway issues, or payment processing failures.",
    ],
  },
  {
    heading: "Disclaimer of warranties and liability",
    items: [
      "The website, services, content, user account, listings, and third-party content are provided on an as-is and as-available basis without warranties of any kind.",
      "GoJobin does not warrant that the website or services will be uninterrupted, timely, secure, error-free, constantly available, complete, true, accurate, or non-misleading.",
      "GoJobin shall not be liable for indirect, punitive, special, exemplary, incidental, or consequential damages including loss of business, revenue, profits, use, data, goodwill, or other intangible losses.",
      "GoJobin liability, if any, shall be limited to the amount of fees paid by the user to GoJobin for the applicable service, subject to applicable law.",
    ],
  },
  {
    heading: "Indemnity and termination",
    items: [
      "Users agree to indemnify and hold harmless GoJobin, its affiliates, associates, owners, directors, officers, agents, employees, partners, and service providers from claims, losses, damages, costs, and expenses arising from violation of law, breach of these Terms, breach of policies, or infringement of third-party rights.",
      "GoJobin may suspend or terminate services, account access, listings, or website access without prior notice for breach of law, policies, guidelines, or these Terms.",
      "On termination, user access may be removed, account information may be disabled, and user content may be removed from the website.",
    ],
  },
  {
    heading: "Governing law and jurisdiction",
    items: [
      "These Terms shall be governed by the laws of India.",
      "Disputes arising from the use of GoJobin or these Terms shall be subject to the jurisdiction of competent courts in India, unless otherwise required by applicable law.",
      "Users accessing GoJobin from outside India do so at their own risk and are responsible for compliance with applicable local laws.",
    ],
  },
  {
    heading: "Contact",
    items: [
      "For questions, comments, complaints, or grievances related to GoJobin, contact info@gojobin.com.",
    ],
  },
];

const paragraphs = sections.flatMap((section) => section.items);

export const metadata = {
  title: "Terms | GoJobin",
  description: "GoJobin terms of use for website access and services.",
};

export default function Terms() {
  return (
    <PolicyPage
      eyebrow="Legal"
      title="Terms"
      intro="These Terms govern access to and use of GoJobin, including job search, recruitment, enquiry, listing, and related services."
      paragraphs={paragraphs}
    />
  );
}
